<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<property name="M_PI" value="3.14159" />
	<property name="base_length" value="1.3" />
	<property name="base_width" value="0.8" />
	<property name="base_height" value="0.2" />
	<property name="base_mass" value="10" />
	<property name="head_mass" value="0.2" />
	<property name="wheel_length" value="0.08" />
	<property name="wheel_radius" value="0.15" />
	<property name="wheel_mass" value="1" />
	<property name="wheel_x_offset" value="0.4" />
	<property name="wheel_y_offset" value="0.375" />
	<property name="wheel_z_offset" value="-0.055" />
	<material name="yellow">
		<color rgba="1 0.4 0 1" />
	</material>
	<material name="black">
		<color rgba="0 0 0 0.9" />
	</material>
	<material name="gray">
		<color rgba="0.75 0.75 0.75 1" />
	</material>
	<material name="white">
		<color rgba="1 1 1 1" />
	</material>
	<material name="blue">
		<color rgba="0 0 .8 1" />
	</material>
	<macro name="cylinder_inertial_matrix" params="m r h">
		<inertial>
			<mass value="${m}" />
			<inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}" />
		</inertial>
	</macro>
	<macro name="retangle_inertial_matrix" params="m d w h">
		<inertial>
			<mass value="${m}" />
			<inertia ixx="${m*(d*d+h*h)/12}" ixy="0" ixz="0" iyy="${m*(d*d+w*w)/12}" iyz="0" izz="${m*(h*h+w*w)/12}" />
		</inertial>
	</macro>
	<macro name="steer_wheel" params="prefix reflect">
		<link name="${prefix}_front_wheel">
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
				<material name="black" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
			</collision>
			<cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
		</link>
		<joint name="${prefix}_front_steer_joint" type="continuous">
			<origin xyz="${wheel_x_offset} ${reflect*wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="${prefix}_front_wheel" />
			<axis xyz="0 1 0" />
		</joint>
		<gazebo reference="${prefix}_front_wheel">
			<material>
				Gazebo/Black
			</material>
		</gazebo>
		<transmission name="${prefix}_wheel_joint_trans">
			<type>
				transmission_interface/SimpleTransmission
			</type>
			<joint name="${prefix}_front_steer_joint">
				<hardwareInterface>
					hardware_interface/VelocityJointInterface
				</hardwareInterface>
			</joint>
			<actuator name="${prefix}_wheel_joint_motor">
				<hardwareInterface>
					hardware_interface/VelocityJointInterface
				</hardwareInterface>
				<mechanicalReduction>
					1
				</mechanicalReduction>
			</actuator>
		</transmission>
	</macro>
	<macro name="drive_wheel" params="prefix reflect">
		<link name="${prefix}_rear_wheel">
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
				<material name="black" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
			</collision>
			<cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
		</link>
		<joint name="${prefix}_rear_drive_joint" type="continuous">
			<origin xyz="${-1*wheel_x_offset} ${reflect*wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="${prefix}_rear_wheel" />
			<axis xyz="0 1 0" />
		</joint>
		<gazebo reference="${prefix}_rear_wheel">
			<material>
				Gazebo/Black
			</material>
		</gazebo>
		<transmission name="${prefix}_wheel_joint_trans">
			<type>
				transmission_interface/SimpleTransmission
			</type>
			<joint name="${prefix}_rear_drive_joint">
				<hardwareInterface>
					hardware_interface/VelocityJointInterface
				</hardwareInterface>
			</joint>
			<actuator name="${prefix}_wheel_joint_motor">
				<hardwareInterface>
					hardware_interface/VelocityJointInterface
				</hardwareInterface>
				<mechanicalReduction>
					1
				</mechanicalReduction>
			</actuator>
		</transmission>
	</macro>
	<macro name="robot_base">
		<link name="head">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size=".12 .13 .04" />
				</geometry>
				<material name="white" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size=".12 .13 .04" />
				</geometry>
			</collision>
			<retangle_inertial_matrix m="${head_mass}" d=".12" w=".13" h=".04" />
		</link>
		<gazebo reference="head">
			<material>
				Gazebo/White
			</material>
		</gazebo>
		<joint name="tobox" type="fixed">
			<origin xyz="0.3 0 0.1" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="head" />
		</joint>
		<link name="lida_rod">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<cylinder length=".4" radius=".02" />
				</geometry>
				<material name="white" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<cylinder length=".4" radius=".02" />
				</geometry>
			</collision>
			<cylinder_inertial_matrix m=".3" r=".02" h=".4" />
		</link>
		<gazebo reference="lida_road">
			<material>
				Gazebo/Gray
			</material>
		</gazebo>
		<joint name="tobox2" type="fixed">
			<origin xyz="0 0 0.2" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="lida_rod" />
		</joint>
		<link name="base_link">
			<visual>
				<geometry>
					<box size="${base_length} ${base_width} ${base_height}" />
				</geometry>
				<origin rpy="0 0 0" xyz="0 0 0" />
				<material name="blue" />
			</visual>
			<collision>
				<geometry>
					<box size="${base_length} ${base_width} ${base_height}" />
				</geometry>
				<origin rpy="0 0 0" xyz="0 0 0" />
			</collision>
			<retangle_inertial_matrix m="${base_mass}" d="${base_length}" w="${base_width}" h="${base_height}" />
		</link>
		<gazebo reference="base_link">
			<material>
				Gazebo/Blue
			</material>
		</gazebo>
		<steer_wheel prefix="left" reflect="1" />
		<steer_wheel prefix="right" reflect="-1" />
		<drive_wheel prefix="left" reflect="1" />
		<drive_wheel prefix="right" reflect="-1" />
		<gazebo>
			<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<rosDebugLevel>
					Debug
				</rosDebugLevel>
				<publishWheelTF>
					true
				</publishWheelTF>
				<robotNamespace>
					/
				</robotNamespace>
				<publishTf>
					1
				</publishTf>
				<publishWheelJointState>
					true
				</publishWheelJointState>
				<alwaysOn>
					true
				</alwaysOn>
				<updateRate>
					100.0
				</updateRate>
				<legacyMode>
					true
				</legacyMode>
				<leftJoint>
					left_rear_drive_joint
				</leftJoint>
				<rightJoint>
					right_rear_drive_joint
				</rightJoint>
				<wheelSeparation>
					0.8
				</wheelSeparation>
				<wheelDiameter>
					${2*wheel_radius}
				</wheelDiameter>
				<broadcastTF>
					1
				</broadcastTF>
				<wheelTorque>
					80
				</wheelTorque>
				<wheelAcceleration>
					3
				</wheelAcceleration>
				<commandTopic>
					cmd_vel
				</commandTopic>
				<odometryFrame>
					odom
				</odometryFrame>
				<odometryTopic>
					odom
				</odometryTopic>
				<robotBaseFrame>
					base_link
				</robotBaseFrame>
			</plugin>
		</gazebo>
		<gazebo>
			<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<rosDebugLevel>
					Debug
				</rosDebugLevel>
				<publishWheelTF>
					true
				</publishWheelTF>
				<robotNamespace>
					/
				</robotNamespace>
				<publishTf>
					1
				</publishTf>
				<publishWheelJointState>
					true
				</publishWheelJointState>
				<alwaysOn>
					true
				</alwaysOn>
				<updateRate>
					100.0
				</updateRate>
				<legacyMode>
					true
				</legacyMode>
				<leftJoint>
					left_front_steer_joint
				</leftJoint>
				<rightJoint>
					right_front_steer_joint
				</rightJoint>
				<wheelSeparation>
					0.8
				</wheelSeparation>
				<wheelDiameter>
					${2*wheel_radius}
				</wheelDiameter>
				<broadcastTF>
					1
				</broadcastTF>
				<wheelTorque>
					80
				</wheelTorque>
				<wheelAcceleration>
					3
				</wheelAcceleration>
				<commandTopic>
					cmd_vel
				</commandTopic>
				<odometryFrame>
					odom
				</odometryFrame>
				<odometryTopic>
					odom
				</odometryTopic>
				<robotBaseFrame>
					base_link
				</robotBaseFrame>
			</plugin>
		</gazebo>
	</macro>
</robot>
